- lib/cli.py
The issue was:
error: argument -v/--pg-version: invalid choice: '13' (choose from 11, 12, 13)
> Fix --pg-version check

- edb-deployment
This argument is not supported on most python versions.
The issue was:
ERROR: Unrecognised argument(s): encoding
> Do not use encoding arg. for setting up logging

- edbdeploy/data/terraform/aws/environments/security/security.tf
- edbdeploy/data/terraform/azure/environments/security/security.tf
- edbdeploy/data/terraform/gcloud/environments/compute/compute.tf
- edbdeploy/data/terraform/gcloud/environments/security/firewall.tf
Updating pooler security groups. This commit allows the following ports:
1. pgpool watchdog
2. pgpool
3. pgbouncer.
With this fix, also added the HTTP port required for pemserver in GCloud.
> Pooler security groups

- scripts/install_requirements_darwin_x64.sh
Updated install requirements for darwin to use curl instead of wget (which is not available by default)
> Updated install requirements for darwin to use curl instead of wget

- edbdeploy/spec/aws.py
Implemented by using a global variable that can be used to define all of
the AWS instance types to add as an option for each system.
> Add the option of aws nano instances for each system

- scripts/install_requirements_darwin_x64.sh
- scripts/install_requirements_linux_x64.sh
At the moment, edb-ansible is not yet ready for Ansible 3, so, we
ensure the installation of the last 2.10.
Azure CLI and Ansible depend on the cryptography module, but the
last version of this python module requires rust for building it.
This is not supported by old pip version, then we pin cyptography
version to 3.3.2, which does not require rust.
> Pin third party tools version

- edbdeploy/project.py
Replaces this error:
+ ERROR: 'NoneType' object has no attribute 'name'
by
+ ERROR: SSH private key not defined
> Verify SSH key options are defined

- edbdeploy/cloud.py
Remove the expectation that the end of the line is immediately after
the version number.  Something it may look like this:
azure-cli                         2.20.0 *
> Update regex for checking azure-cli version

- README.md
- edbdeploy/cli.py
- edbdeploy/command.py
- edbdeploy/commands/aws.py
- edbdeploy/commands/baremetal.py
- edbdeploy/options.py
- edbdeploy/project.py
- edbdeploy/spec/baremetal.py
- edbdeploy/specifications.py
- setup.py
This PR allows to deploy the reference architectures on already provisioned infrastructure, ie: baremetal servers, local VMs, etc..
The new cloud vendor `baremetal` is added:
```shell
$ edb-deployment baremetal <sub-command> [options] <project-name>
```
IP address configuration must be done with the help of the specifications mechanism:
1.  Dump default specs for the target ref. architecture:
```shell
$ edb-deployment baremetal specs --reference-architecture EDB-RA-1 > ~/bare1.json
```
2. Configure IP addresses in `~/bare1.json`:
```json
{
"ssh_user": null,
"pg_data": null,
"pg_wal": null,
"postgres_server_1": {
"name": "pg1",
"public_ip": "192.168.122.23",
"private_ip": "192.168.122.23"
},
"pem_server_1": {
"name": "pem1",
"public_ip": "192.168.122.24",
"private_ip": "192.168.122.24"
}, …
```
> Baremetal support

- edbdeploy/project.py
The setting of the terraform variable for hammerdb_server is meant for
another set of patches.
> Remove unintentional change to gcloud provisioning

- edbdeploy/commands/aws.py
- edbdeploy/data/terraform/gcloud/environments/compute/compute.tf
- edbdeploy/data/terraform/gcloud/environments/compute/outputs.tf
- edbdeploy/data/terraform/gcloud/main.tf
- edbdeploy/data/terraform/gcloud/variables.tf.template
- edbdeploy/options.py
- edbdeploy/project.py
- edbdeploy/spec/gcloud.py
Now that each supported cloud vendor is supported, no need for separate
ReferenceArchitectureOption per vendor.
Also updated the min/max storage options to match the vendor's allowed
min/max values.
> Add hammerdb architecture to gcloud

- edbpotdeploy/project.py
In this case, PEM user is postgres, not enterprisedb.
> Fix display sub-command when --pg-type=PG

- edbpotdeploy/data/ansible/roles/pot_setup/vars/PG.yml
edb-ansible collection configure by default the PostgreSQL Unix
socket path to /var/run/postgresql
> Fix Unix socket dir

- edbdeploy/data/terraform/azure-db/environments/vm/vm.tf
- edbdeploy/project.py
- edbdeploy/spec/azure_db.py
The sku, or instance type, for the Azure DB Single System wasn't being
set correctly from the json configuration file.  This also cleans up
the spec validator for a valid storage size.
> Fix use of sku for Azure DB

- edbdeploy/cloud.py
awscli versions 2.x are not and won't be published on pypi. Versions
1.x are still maintained so far, we stay on 1.x for now.
> Support awscli version 1.x only

- edbdeploy/terraform.py
Due to some compatibily breaks in previous terraform versions, we
ensure to support only the 1.0.0 (and upper in the future) version.
Random failure exemple with 0.15.4:
```
Error: file provisioner error
with module.edb-db-cluster.null_resource.barman_copy_setup_volume_script[0],
on environments/ec2/ec2.tf line 271, in resource "null_resource" "barman_copy_setup_volume_script":
271:   provisioner "file" {
host for provisioner cannot be empty
```
> Support terraform 1.0.0 only

- edbdeploy/ansible.py
When executing ansible-inventory command to prevent eventual warning
messages making the output not JSON compatible when python version
is < 3.8
> Set ANSIBLE_DEPRECATION_WARNINGS to false

- edbdeploy/project.py
Ansible variable ansible_ssh_pass must be only set when deploying
on vmware machines. For the other cloud vendors, deployment was
broken with the following message:
fatal: [primary1]: FAILED! => {"msg": "to use the 'ssh' connection
type with passwords, you must install the sshpass program"}
> Fix ansible_ssh_pass setting

- edbdeploy/projects/aws_rds_aurora.py
By calling the __init__() method of AWSRDSProject parent's (which is
Project) instead of AWSRDSAuroraProject's parent (which is
AWSRDSProject).
In both cases, __init__() signature was not the same.
> Fix AWSRDSAuroraProject's __init__ method

- edbdeploy/ansible.py
Enabling pipelining reduce deployment duration of the EDB-RA-2
architecture from 23 minutes to 10 minutes.
> Enable Ansible pipelining

- edbdeploy/data/ansible/EDB-Always-On.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/defaults/main.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/os_configure_user.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pem_server_certs.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pem_server_probe_alert.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_pot_scripts.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_user_pgpass.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/barman-backup-monitor.py.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/data_view.sql
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/haproxy-pgbouncer-monitor.sh.templates
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_bdr_probe.sql.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_charts.sql.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.template
- edbdeploy/data/terraform/aws/environments/ec2/outputs.tf
- edbdeploy/data/tpaexec/hooks/pre-initdb.yml
Adding the following capability in aws-pot:
1. Probes and files for monitoring HAproxy, pgbouncer and Barman
2. Dashboard and charts for PEM
3. Environment configuration for client
> Adding more capabilities for BDR Always On PoT

- edbdeploy/data/ansible/EDB-Always-On.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_pot_hba.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/haproxy-pgbouncer-monitor.sh.templates
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.template
- edbdeploy/data/terraform/aws/environments/ec2/outputs.tf
This commit allows the following:
1. Makes pgbouncer to run in transaction pool_mode
2. Register database through pgbouncer
4. Groups pgbouncer registered dbs in correct DCs
> BDR PoT pgbouncer integration

- edbdeploy/__init__.py
- edbdeploy/commands/aws_pot.py
- edbdeploy/data/terraform/aws/environments/ec2/outputs.tf
- edbdeploy/options.py
- edbdeploy/project.py
This commit made the following changes:
1. Remove the EDB-Always-On architecture option from azure and gcloud.
2. Bumped the version to 3.5.0
3. Add pemserver1 in ssh_config file of tpaexec
> AWS BDR PoT final

- edbdeploy/spec/reference_architecture.py
This commit fixes the EDB-RA-3 architecture issue due to typo EDB-RA-3 Specification
> Fixing typo in EDB-RA-3 architecture spec

- edbdeploy/data/ansible/EDB-Always-On.yml
- edbdeploy/data/ansible/POT-Remove-Project-Route53.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/update_route53.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_probe_alert.sql
- edbdeploy/project.py
- edbdeploy/projects/aws_pot.py
- edbdeploy/projects/azure_pot.py
- edbdeploy/projects/gcloud_pot.py
Fixing the PoT route53 removal based on the destroy project. Also, ensuring BarmanDC servers should not be part of server binding.
> PoT route53 fixes and PEM server

- edbdeploy/command.py
- edbdeploy/commands/aws.py
- edbdeploy/commands/aws_pot.py
- edbdeploy/commands/azure.py
- edbdeploy/commands/azure_pot.py
- edbdeploy/commands/baremetal.py
- edbdeploy/commands/default.py
- edbdeploy/commands/gcloud.py
- edbdeploy/commands/gcloud_pot.py
- edbdeploy/commands/virtualbox.py
- edbdeploy/commands/vmware.py
- edbdeploy/project.py
Usage: edb-deployment <cloud> ssh <project-name> <node-name>
node-name is the hostname (not the FQDN) of the target machine, can
be: pemserver1, pgsql1, pgsql2, etc...
The SSH user used is the one used to deploy the components.
> Adding the ssh sub-command

- README.md
- edbdeploy/command.py
- edbdeploy/commands/aws_pot.py
- edbdeploy/commands/azure_pot.py
- edbdeploy/commands/default.py
- edbdeploy/commands/gcloud_pot.py
- edbdeploy/data/terraform/aws/environments/ec2/outputs.tf
- edbdeploy/data/terraform/azure/environments/vm/outputs.tf
- edbdeploy/data/terraform/gcloud/environments/compute/outputs.tf
- edbdeploy/project.py
- edbdeploy/specifications.py
This sub-command is only available for PoT deployments. It makes a copy of the SSH private keys, and the ssh_config file, into the current directory.
> Adding the get_ssh_keys sub-command

- edbdeploy/data/ansible/POT-Remove-Project-Route53.yml
Fixing the pemserver public ip address issue in POT-Remove Route53 playbook
> Fixing the pemserver public ip address issue in POT-Remove Route53 playbook

- edbdeploy/data/ansible/roles/pot_setup/defaults/main.yml
Fixing the efm_cluster_name issue due to change in edb-ansible efm_cluster_name. Issue is reported by Borris and affecting non-bdr PoT.
> Fixing the efm_cluster_name issue due to change in edb-ansible efm_cluster_name

- edbdeploy/project.py
Dot not check instance type availability if the number of machine
is zero.
> Fixes Project._get_instance_types()

- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/os_configure_user.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/sudo_user.template
This PR allows a project user to execute commands like:
1. `sudo barman check all`
2. `sudo barman list-backup all`
3. `sudo barman list-backup all`
etc.
> Adding the permision for barman execution as a project user

- edbdeploy/data/ansible/EDB-Always-On-Platinum.yml
- edbdeploy/data/ansible/EDB-Always-On-Silver.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pem_server_certs.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_create_user.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_bdr_probe.sql.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.platinum.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.silver.template
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_probe_alert.sql
- edbdeploy/data/templates/config.yml.j2
- edbdeploy/data/tpaexec/hooks/post-deploy.yml
- edbdeploy/data/tpaexec/hooks/pre-initdb.yml
This commit fixes the following for BDR PoT:
1. PEM default dashboards, which are not supporting BDR 4.0 due to probe code, we fixed that using ansible. We also hope the next release of PEM will have a fix for that
2. config.yml.j2 has been optimized as per the new structure supported by tpaexec, i.e., we don't need a primary role for bdr nodes.
3. pemagent has got extra monitoring permissions for BDR
4. As per the new HARP 2.0, we don't install edb-server packages/binaries on the pgbouncer node. Due to which custom dashboards were broken. We have modified the role to ensure edb-server packages are installed on the pgbouncer node
5. Enable pgbouncer monitoring as remote database monitoring.
6. Fix the problem with PEM server where localhost for 1PV6 may not redirect requests to the …
> BDR PoT fixes for PEM

- edbdeploy/command.py
- edbdeploy/commands/aws_pot.py
- edbdeploy/commands/azure_pot.py
- edbdeploy/commands/default.py
- edbdeploy/commands/gcloud_pot.py
- edbdeploy/project.py
This subcommand can be used to update project's route53 access key
and secret. Available only for *-pot.
> update_route53_key new subcommand

- edbdeploy/data/templates/config.yml.j2
Without this change, Harp packages cannot be found and installed.
> Explicitly defines Harp repository

- edbdeploy/data/terraform/azure-db/versions.tf
Duplicate required_providers causes terraform to throw an error.
> Remove duplicate required_providers

- edbdeploy/cloud.py
- edbdeploy/options.py
- edbdeploy/projects/aws_pot.py
- edbdeploy/projects/azure_pot.py
- edbdeploy/projects/gcloud_pot.py
- edbdeploy/spec/__init__.py
Adding RockyLinux support for PoT. This doesn't solve BDR PoT issue. However, enabled edb-deployment for RockyLinux and as soon as TPAExec supports Rocky Linux, BDR PoT will be automatically supported
> Rocky Linux support for PoT

- edbdeploy/data/templates/config.yml.j2
TPAexec v22.9 does not configure pgbouncer as the default proxy
mode for Harp.
> BDR: force default_harp_proxy_mode to pgbouncer

- edbdeploy/data/tpaexec/hooks/post-deploy.yml
Do not try to reconfigure pgbouncer and Harp on witness and
read-only BDR nodes.
> Fix BDR PoT Platinum deployment

- edbdeploy/data/ansible/EDB-RA-1.yml
EDB-RA-1 deployment was failing due to the inclusion of the
setup_dbt2 role. There is no need for DBT2 usage with this
architecture.
The error message was:
TASK [edb_devops.edb_postgres.setup_dbt2 : Gather DBT-2 driver addresses] ******
FAILED! => {"msg": "'dict object' has no attribute 'dbt2_driver'"}
Reported by: Sergio Romera
> Fix EDB-RA-1

- edbdeploy/cloud.py
- edbdeploy/spec/__init__.py
The previous filter led to wrong AMI ID in some cases.
> Update AWS filter used to fetch Rocky8 AMI ID

- edbdeploy/projects/virtualbox.py
"On Linux, Mac OS X and Solaris Oracle VM VirtualBox will only allow IP addresses in 192.168.56.0/21 range to be assigned to host-only adapters."
https://www.virtualbox.org/manual/ch06.html#network_hostonly
An alternative is to edit the VirtualBox configuration file but I think we prefer to minimize user required configuration.
> Update virtualbox host-only networking

- README.md
- VIRTUALBOX.md
- edbdeploy/data/templates/Vagrantfile.j2
- edbdeploy/projects/virtualbox.py
- edbdeploy/render.py
- edbdeploy/spec/virtualbox.py
- edbdeploy/virtualbox.py
Use of jinja2 generated template file for Vagrantfile
- spec file used to specify os/os-image and starting ipv4 for vms
- Vagrantfile.j2 template stored in data/templates and variables generated with spec file or environment variables
Closes #345
Resolves #339
Resolves #341
> VirtualBox: template generation for Vagrantfile and specs support for os options, vagrantbox image and starting ipv4 for vms to use

- README-WIN.md
- README.md
- VIRTUALBOX.md
- edbdeploy/data/templates/Vagrantfile.j2
- edbdeploy/projects/virtualbox.py
- edbdeploy/render.py
- edbdeploy/spec/virtualbox.py
- edbdeploy/virtualbox.py
VirtualBox changes:
* Jinja2 template generation for Vagrantfile
* vagrant init removed since vagrantfile is used
* Specs including dbt2 specs created and ips assigned during configure subcommand instead of provision subcommand
* Removed unused hook since Project.provision() is overridden
* New specs saved into project directory
* Spec file loaded during provision subcommand
* Docs updated
Revert PR: #349
Original PR: #345
> VirtualBox: template generation for Vagrantfile and specs support for os options, vagrantbox image and starting ipv4 for vms to use - Rework

- edbdeploy/ansible.py
Note: starting from ansible 2.12, minimal Python version is 3.8. It means, the setup command won't work if the Python version is lower than 3.8.
> Update max ansible version to 2.12.10

- edbdeploy/cloud.py
`gcloud auth login <LOGIN_EMAIL> --no-launch-browser` error while trying to retrieve token when using older CLI version installed w/ `edb-deployment gcloud setup`
```
Authorization Error
Error 400: invalid_request
The version of the app you're using doesn't include the latest security features to keep you protected. Please make sure to download from a trusted source and update to the latest, most secure version.
```
> bump GCloudCli max_version

- edbdeploy/__init__.py
- edbdeploy/data/ansible/EDB-Always-On-Platinum.yml
- edbdeploy/data/ansible/EDB-Always-On-Silver.yml
- edbdeploy/data/ansible/EDB-RA-1.yml
- edbdeploy/data/ansible/EDB-RA-2.yml
- edbdeploy/data/ansible/EDB-RA-3.yml
- edbdeploy/data/ansible/EDB-RA.yml
- edbdeploy/options.py
Adding support from EFM 4.5 and making this version default for all EDB-RA architectures Also made edb-ansible 3.16 as a default version
> EFM 4.5 and EDB Ansible 3.16 support

- edbdeploy/__init__.py
- edbdeploy/data/ansible/EDB-Always-On-Platinum.yml
- edbdeploy/data/ansible/EDB-Always-On-Silver.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/os_configure_user.yml
- edbdeploy/data/ansible/roles/bdr_pot_setup/templates/harp-proxy-pgbouncer-monitor.sh.templates
- edbdeploy/options.py
- edbdeploy/tpaexec.py
This PR pushes the following changes
1. Bump the postgres-deployment version
2. Make postgres-deployment to use latest version of edb-ansible
3. Use the latest version of PEM 9.0.0
4. BDR POt has monitoring of HARP/ETCD
5. Added support for latest version of TPAExec for BDR PoT
> Update for postgres-deployment
