lib/project.py

When project cloud resources are still present.

Prevent project deletion

---

edbdeploy/cli.py
edbdeploy/command.py
edbdeploy/project.py

This commit brings the displaying the password capability in CLI

Adding display password capability in CLI

---

edbdeploy/cli.py
edbdeploy/project.py

Adding argument `--efm-version` in CLI

Exposing efm_version as an argument through cli

---

README.md
edbdeploy/cli.py
edbdeploy/data/ansible/HammerDB-TPROC-C.yml
edbdeploy/data/terraform/aws/environments/ec2/ec2.tf
edbdeploy/data/terraform/aws/environments/ec2/outputs.tf
edbdeploy/data/terraform/aws/environments/routes/routes.tf
edbdeploy/data/terraform/aws/main.tf
edbdeploy/data/terraform/aws/variables.tf.template
edbdeploy/project.py
edbdeploy/spec/aws.py
edbdeploy/spec/reference_architecture.py

This prepares a set of 2 systems, 1 database system and 1 system to
drive with HammerDB for testing with TPCROC-C.

Add HammerDB-TPROC-C architecture

---

edbdeploy/data/terraform/aws/environments/ec2/add_ips_to_hosts.sh
edbdeploy/data/terraform/aws/environments/ec2/ec2.tf
edbdeploy/data/terraform/aws/environments/security/security.tf

PER-10 v2 - Add meaningful hostnames to AWS PG/EPAS Cluster Instances

PER-10 v2 - Add meaningful hostnames to AWS PG/EPAS Cluster Instances

---

edbdeploy/project.py

AWS RDS & Aurora: improve display sub-command

---

edbdeploy/cli.py
edbdeploy/data/terraform/aws-rds-aurora/environments/aws/aws.tf
edbdeploy/data/terraform/aws-rds-aurora/main.tf
edbdeploy/data/terraform/aws-rds-aurora/variables.tf.template
edbdeploy/data/terraform/aws-rds/environments/aws/aws.tf
edbdeploy/data/terraform/aws-rds/main.tf
edbdeploy/data/terraform/aws-rds/variables.tf.template
edbdeploy/password.py
edbdeploy/project.py

RDS/Aurora: generate master user password

---

README.md
edbdeploy/command.py
edbdeploy/commands/aws.py
edbdeploy/commands/azure.py
edbdeploy/commands/gcloud.py
edbdeploy/project.py

This commits add the ansible-playbook pre/post host in edb-deployment

Adding the feature for pre and post ansible hooks

---

edbdeploy/project.py

For the sake of readability, maintainability and scale.
Splitting the "configure" sub-command code and exploding
build_terraform_vars()'s code into Cloud vendor dedicated
methods.

Refactoring configure() and build_terraform_vars()

---

edbdeploy/commands/azure.py
edbdeploy/data/terraform/azure/environments/security/security.tf
edbdeploy/data/terraform/azure/environments/vm/outputs.tf
edbdeploy/data/terraform/azure/environments/vm/vm.tf
edbdeploy/data/terraform/azure/main.tf
edbdeploy/data/terraform/azure/variables.tf.template
edbdeploy/options.py
edbdeploy/project.py
edbdeploy/spec/azure.py

Add additional resources to the terraform scripts so that a dedicated system for running HammerDB can be provisioned to run the TPROC-C workload.

Support HammerDB architecture with Azure Virtual Machines

---

README.md
edbdeploy/ansible.py
edbdeploy/cloud.py
edbdeploy/terraform.py

**Support for latest versions:**
- ansible 2.10.8
- terraform 0.15.1
- aws 2.0.45
- azure 2.23.0
- google cloud 329.0.0

Support for latest ansible,terraform,aws,azure and google cloud versions

---

edbdeploy/cli.py
edbdeploy/cloud.py
edbdeploy/command.py
edbdeploy/commands/vmware.py
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-1/Mechfile
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-1/playbook.yml
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-2/Mechfile
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-2/playbook.yml
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-3/Mechfile
edbdeploy/data/vmware-wkstn/centos8/EDB-RA-3/playbook.yml
edbdeploy/errors.py
edbdeploy/options.py
edbdeploy/project.py
edbdeploy/spec/vmware.py
edbdeploy/specifications.py
edbdeploy/vmware.py
setup.py

Changes:
- Updated Ansible maximum version
- Updated Terraform maximum version
- Integrated into branch edb-cli 'vmware' support

Updated Ansible, Terraform versions. Integrated with edb-cli 'vmware'

---

edbdeploy/ansible.py

We do not execute the ansible --version command anymore, instead
we import the __version__ variable from ansible python module.
This commit updates ansible's max_version to 2.11.1

Update ansible version parsing

---

edbdeploy/options.py

argparse is needed from some of the error handling.

import argparse

---

edbdeploy/cloud.py
edbdeploy/terraform.py

Changes:
- Support for Terraform v1.0.0
- Azure CLI v2.25.0

Support for Terraform v1.0.0 and Azure CLI v2.25.0

---

edbdeploy/ansible.py

Previous version checking method based on ansible module import
was not reliable when ansible was installed through the setup
command.
Back to the ansible --version method, but now we are able to parse
ansible version coming from old and new releases.
ansible-base pypi package is now replaced by ansible-core.

Update ansible version checking

---

edbdeploy/terraform.py

Fix the following error when azure cli is installed with the setup
sub-command:
Error launching Azure CLI: exec: "az": executable file not found
in $PATH

PATH env. var. update when executing terraform

---

README.md
edbdeploy/ansible.py
edbdeploy/cli.py
edbdeploy/cloud.py
edbdeploy/commands/aurora.py
edbdeploy/commands/azure.py
edbdeploy/commands/azure_db.py
edbdeploy/commands/gcloud_sql.py
edbdeploy/commands/rds.py
edbdeploy/data/ansible/HammerDB-DBaaS.yml
edbdeploy/data/terraform/gcloud-sql/environments/compute/compute.tf
edbdeploy/data/terraform/gcloud-sql/environments/compute/outputs.tf
edbdeploy/data/terraform/gcloud-sql/environments/network/network.tf
edbdeploy/data/terraform/gcloud-sql/environments/security/firewall.tf
edbdeploy/data/terraform/gcloud-sql/main.tf
edbdeploy/data/terraform/gcloud-sql/provider.tf
edbdeploy/data/terraform/gcloud-sql/variables.tf.template
edbdeploy/data/terraform/gcloud-sql/versions.tf
edbdeploy/options.py
edbdeploy/project.py
edbdeploy/spec/gcloud_sql.py
edbdeploy/specifications.py

Provision and deploy Google Cloud SQL for evaluation.

Add gcloud-sql subcommand

---

edbdeploy/terraform.py

Change Log:
- Added support for Terraform v1.0.1

Added support for Terraform v1.0.1

---

edbdeploy/command.py
edbdeploy/commands/rds.py
edbdeploy/project.py
edbdeploy/projects/aws.py
edbdeploy/projects/aws_rds.py
edbdeploy/projects/aws_rds_aurora.py
edbdeploy/projects/azure.py
edbdeploy/projects/azure_db.py
edbdeploy/projects/baremetal.py
edbdeploy/projects/gcloud.py
edbdeploy/projects/gcloud_sql.py
edbdeploy/projects/vmware.py
setup.py

Specific code of cloud vendor is now located in multiple classes
inheriting from Project class.
2 ways for executing specific code:
1. Classic method overloading.
2. Code injection using a new hook mechanism.

Extract cloud specific code from project.py

---

edbdeploy/command.py
edbdeploy/commands/vmware.py
edbdeploy/options.py
edbdeploy/project.py
edbdeploy/projects/vmware.py
edbdeploy/vmware.py

EFM Version 4.1 Does not work with VMWare during deploy
No longer using EDB-RA-1-3 folder structure because it takes up space

Fixed List Command and EFM Versioning for VMWare

---

edbdeploy/cli.py
edbdeploy/cloud.py
edbdeploy/command.py
edbdeploy/commands/azure_pot.py
edbdeploy/commands/gcloud_pot.py
edbdeploy/data/ansible/PoT-EDB-RA-2.yml
edbdeploy/data/ansible/roles/pot_setup/defaults/main.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/efm_scripts_rules.yml
edbdeploy/data/ansible/roles/pot_setup/templates/efm_rewind.sh.template
edbdeploy/data/terraform/azure/main.tf
edbdeploy/options.py
edbdeploy/project.py
edbdeploy/projects/azure_pot.py
edbdeploy/projects/gcloud_pot.py
edbdeploy/specifications.py

Adding the PoT support for other clouds

---

edbdeploy/ansible.py
edbdeploy/command.py
edbdeploy/commands/aurora.py
edbdeploy/commands/aws.py
edbdeploy/commands/aws_pot.py
edbdeploy/commands/azure.py
edbdeploy/commands/azure_db.py
edbdeploy/commands/azure_pot.py
edbdeploy/commands/baremetal.py
edbdeploy/commands/gcloud.py
edbdeploy/commands/gcloud_pot.py
edbdeploy/commands/gcloud_sql.py
edbdeploy/commands/rds.py
edbdeploy/commands/vmware.py
edbdeploy/project.py
edbdeploy/projects/aws_pot.py
edbdeploy/projects/azure_pot.py
edbdeploy/projects/gcloud_pot.py

Pipelining will be effective by default and can be disabled with the help of the `--disable-pipelining` option

Enable Ansible pipelining

---

edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_probe_alert.sql
edbdeploy/data/ansible/roles/pot_setup/defaults/main.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/main.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/os_configure_user.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/pem_server_probe_alert.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/pg_create_user.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/pg_hba_rule.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/pg_pot_hba.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/pg_user_pgpass.yml
edbdeploy/data/ansible/roles/pot_setup/tasks/verify_variables.yml
edbdeploy/data/ansible/roles/pot_setup/templates/pem_probe_alert.sql
edbdeploy/data/ansible/roles/pot_setup/templates/pg_env_dbserver.sh.template
edbdeploy/projects/aws_pot.py
edbdeploy/projects/azure_pot.py
edbdeploy/projects/gcloud_pot.py
edbdeploy/spec/reference_architecture.py

Fixing some issues of PoT EDB-RA and issues came due to support of dbt2

DBT2 fixes for POT

---

edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_create_user.yml
edbdeploy/data/tpaexec/hooks/post-deploy.yml

Adding the fix for Postgres service alias

BDR fix for service alias

---

edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pg_pot_scripts.yml
edbdeploy/data/ansible/roles/pot_setup/vars/EPAS.yml
edbdeploy/data/tpaexec/hooks/post-deploy.yml

Fixing the missing pg_pot_scripts

Fixing the missing pg_pot_scripts

---

edbdeploy/data/terraform/aws/environments/ec2/outputs.tf

Rollback pgbouncer_pool_mode to default value

Rollback pgbouncer_pool_mode to default value

---

edbdeploy/__init__.py
edbdeploy/data/ansible/EDB-RA-1.yml
edbdeploy/data/ansible/EDB-RA-2.yml
edbdeploy/data/ansible/EDB-RA-3.yml
edbdeploy/data/ansible/EDB-RA.yml
edbdeploy/data/terraform/aws/environments/ec2/setup_volume.sh
edbdeploy/data/terraform/azure/environments/vm/setup_volume.sh
edbdeploy/data/terraform/gcloud/environments/compute/setup_volume.sh
edbdeploy/projects/aws.py

DBT2 changes made default server creation for dbt2 in all the EDB-RA-* architecture. This commit fixes this.
This commit also fixes the volume issue report by Jan in AWS environment

Fix for DBT2 issues in AWS architectures

---

edbdeploy/data/ansible/EDB-Always-On.yml
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.template
edbdeploy/data/ansible/roles/pot_setup/templates/pem_probe_alert.sql
edbdeploy/project.py
edbdeploy/projects/aws_pot.py
edbdeploy/projects/azure_pot.py
edbdeploy/projects/gcloud_pot.py

Fixing the BDR pot and Standard POT issues. Also, stick the new ansible version

BDR PoT fixes and standard PoT fixes

---

edbdeploy/cli.py

Reducing the amount of code by using a map between cloud vendor
codes and their title and sub-command definition.

cli.py refactoring

---

edbdeploy/data/ansible/EDB-Always-On.yml

Updating the PEM Server version in PoT

Updating the PEM Server version in PoT

---

edbdeploy/__init__.py

edb-deployment: 3.7.0.dev1
edb-ansible: 3.6.2

 Update version numbers on master

---

edbdeploy/data/ansible/roles/bdr_pot_setup/defaults/main.yml
edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/os_configure_user.yml
edbdeploy/data/ansible/roles/bdr_pot_setup/tasks/pem_server_probe_alert.yml
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/harp-proxy-pgbouncer-monitor.sh.templates
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_bdr_probe.sql.template
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_charts.sql.template
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.platinum.template
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_dashboards.sql.silver.template

HAProxy probes and dashboard removed.

PoT: Update PEM 8.2 probes and dashboard with Harp 2.0

---

edbdeploy/commands/aws_pot.py
edbdeploy/data/ansible/roles/bdr_pot_setup/templates/pem_bdr_probe.sql.template
edbdeploy/data/terraform/azure/environments/vm/outputs.tf
edbdeploy/data/terraform/azure/environments/vm/vm.tf
edbdeploy/data/terraform/azure/main.tf
edbdeploy/data/terraform/azure/variables.tf.template
edbdeploy/data/terraform/gcloud/environments/compute/compute.tf
edbdeploy/data/terraform/gcloud/environments/compute/outputs.tf
edbdeploy/data/terraform/gcloud/environments/security/firewall.tf
edbdeploy/data/terraform/gcloud/main.tf
edbdeploy/options.py
edbdeploy/projects/azure_pot.py
edbdeploy/projects/gcloud_pot.py

With this PR we are adding support for Azure and GCloud

BDR PoT support for Azure and GCloud

---

edbdeploy/data/templates/inventory.yml.j2
edbdeploy/project.py

Set a flag for dbt2 in the database nodes if it is set in the spec file.

Update inventory template for dbt2

---

edbdeploy/cloud.py
edbdeploy/data/terraform/azure/environments/vm-rocky/outputs.tf
edbdeploy/data/terraform/azure/environments/vm-rocky/setup_volume.sh
edbdeploy/data/terraform/azure/environments/vm-rocky/vm-rocky.tf
edbdeploy/data/terraform/azure/main.tf
edbdeploy/data/terraform/azure/provider.tf
edbdeploy/data/terraform/azure/variables.tf.template
edbdeploy/options.py
edbdeploy/projects/azure.py
edbdeploy/spec/__init__.py

Added RockyLinux OS option to Postgres Deployment

Rockylinux

---

edbdeploy/data/tpaexec/hooks/post-deploy.yml

Fixing some more issues with HARP pgbouncer configuration

Fixing some more issues with HARP pgbouncer configuration and TPAexec

---

edbdeploy/data/ansible/EDB-Always-On-Platinum.yml
edbdeploy/data/ansible/EDB-Always-On-Silver.yml
edbdeploy/data/ansible/EDB-RA-1.yml
edbdeploy/data/ansible/EDB-RA-2.yml
edbdeploy/data/ansible/EDB-RA-3.yml
edbdeploy/data/ansible/EDB-RA.yml

Updating PoT and EDB-RA-* playbooks based on the integration of pemagent and barman in edb-ansible.

Barman and Pemagent integration for PEM.

---

edbdeploy/cloud.py
edbdeploy/spec/__init__.py

Reverts EnterpriseDB/postgres-deployment#330

Revert "Update AWS filter used to fetch Rocky8 AMI ID"

---

edbdeploy/ansible.py

2.10.x no longer works with what we need.

Bump minimal supported anisble version

---

edbdeploy/data/ansible/EDB-RA-1.yml

This reverts commit 7aacec204dd9fcb120742c02a7cf1c773576af5c.

Revert "Fix EDB-RA-1"
